### ISSUE TITLE
Unable to determine strand error

### ISSUE THREAD

**Issue by ghost** [dpryan79/PileOMeth#13]
I receive the following error when attempting to run PileOMeth:

```PileOMeth: common.c:78: updateMetrics: Assertion `strand != 0' failed.
/sge/middle_earth/spool/n26vm1/job_scripts/1089854: line 1: 11686 Aborted                 (core dumped) PileOMeth extract --CHG --CHH genome.fa x.bam```

Sample lines from my BAM file (the file is valid according to Picard's ```ValidateSamFile```):

```
SRR299053.60865334	16	chr10	3002236	38	100M	*	0	0	TAAATCTAAAAATATTCATTCACTACCGCCACCTAACTACCTCACATTTAATATTAACTAAAACAAATACTATTATAAACATCTACGATACACAAAAACT	########B?CC-CC9:<=9:CD:@EDEEEBEECECAEBEF?DEDGBGEFGEGAFGGGDGEFFFFGGGEGGGFGGEEEEDGDGFGGGGGGGGGGGGGGGG	NM:i:0	MD:Z:100	AS:i:100	XS:i:85	RG:Z:G1	XA:Z:rchr10,-3044656,100M,5;	YC:Z:CT	YD:Z:r
SRR299053.61911728	0	chr10	3002249	60	100M	*	0	0	GTTTATTTATTATCGTTATTTGGTTATTTTATATTTAGTGTTGATTGAAGTAGATGTTGTTGTAGGTATCTGCGGTGTATAGAGGTTTAATTTATATAAG	EEEEEEFGEGGEGGGGGAGDEEEEEEEEEC>FAFFEEEEEFFFDFGGFGGFFGFGGFGGFGGBEGEEEFEEGGDGFDGBG?E=EACA?:5?BB:B>?###	NM:i:0	MD:Z:100	AS:i:100	XS:i:23	RG:Z:G1	YC:Z:CT	YD:Z:f
SRR299053.22449369	16	chr10	3002253	31	100M	*	0	0	ATTCACTACCGCCACCTAACTACCTCACATTTAATATTAACTAAAACAAATACTATTATAAACATCTACGATACACAAAAACTCAATCCACACAAAAAAA	B=46>C@7ACCCCCCEDEEEECEEEFCDFEECEECEEBEEF;EEFECFFFEDDFFGGGEGEEDEEGGEFGGGGFGFFFFFFFFFFGEGGGGGGGGGGGGG	NM:i:0	MD:Z:100	AS:i:100	XS:i:88	RG:Z:G1	XA:Z:rchr10,-3044673,100M,4;	YC:Z:CT	YD:Z:r
SRR299053.9560181	16	chr10	3002286	23	100M	*	0	0	ATATTAACTAAAACAAATACTATTATAAACATCTACAATACACAAAAACTCAATCCACACAAAAAAAACAAACACAATTATTATCAACATTTAAAACATA	B:==:EEB8BABA4CCA?>ACDB=DABBAAB@BA@BEEEBA?EEEFFEFDEEEBEFDE?EGGGGGCFFFFEEECEFFF?FFFGBGGGFGGGGGGGGGGGG	NM:i:0	MD:Z:100	AS:i:100	XS:i:91	RG:Z:G1	XA:Z:rchr10,-3044706,100M,3;	YC:Z:CT	YD:Z:r
```

My best guess is that this is from [line 51 of common.c](../blob/master/common.c#L51) returning 0. It is not clear to me why that line does not return 4 instead (i.e. default to single-end forward in this instance).

I'd appreciate any insight into this that you might be able to provide.

**Comment by dpryan79** [comment]
I guess it shows that we only ever use paired-end datasets. Thanks for pointing out this bug, you're absolutely correct on what caused it. The correct value returned should have been 1 (original top strand) and I just pushed a commit to make that the case. Please let me know if you run into issues!
