### ISSUE TITLE
PileOMeth extract option to filter low coverage reads and bases

### ISSUE THREAD

**Issue by Shicheng-Guo** [dpryan79/PileOMeth#19]
Usually, when we call methylation frequency in some region or specific CpG site, the depth of the coverage should be higher than > 5 or > 10 so that the methylation level was creditable. I think PileOMeth extract should add this option.

**Comment by ttriche** [comment]
so send a pull request?

the implementation is not rocket surgery, see for example
https://github.com/zwdzwd/biscuit/blob/master/src/vcf2bed.c


--t

**Comment by dpryan79** [comment]
I've not yet tested it, but this is such a simple thing to implement that I was able to add a branch that will likely work. Feel from to give the "min_depth" branch a try.

**Comment by dpryan79** [comment]
I just fixed a bug with this in the 0.1.11 release. Sorry if you were trying to use it previously and it wasn't working!
