### ISSUE TITLE
Failed reads

### ISSUE THREAD

**Issue by will-NYGC** [dpryan79/PileOMeth#25]
Does PileOMeth ignore the QC-failed reads flag?

**Comment by dpryan79** [comment]
No, since they're rarely included in fastq files. I could add an option to include them and make them ignored by default in the next release, but currently they're included if they're there and pass the MAPQ threshold.

If such behavior would be useful for you then just let me know. I can implement something like that in about 15 minutes.

**Comment by will-NYGC** [comment]
I'm doing some postprocessing on BAMs with our own custom filters and instead of throwing away reads, converting their q-scores or making them N's, i'd like to just flag them as "QC-failed". I'm also using BWA-meth for alignment which also flags reads as QC-failed. 

If you wouldn't mind adding a switch, that would be great.

appreciate your help.

**Comment by dpryan79** [comment]
Will do. I'll default to ignoring them and add a switch to have them included. New version coming shortly...

**Comment by dpryan79** [comment]
Oh, I'd forgotten that QC-failed alignments are already skipped. I guess I should have documented that. Likewise, secondary alignments are skipped (I'll add supplemental alignments to that for the next release). Do you ever want QC-failed reads included? If so I'll finished adding a `--keepQCFail` switch. If not, I'll document the current behavior and close the issue.

**Comment by dpryan79** [comment]
I've opted for an `-F`/`--ignoreFlags` option that identical to what `-F` in samtools view does. I'll keep the default of ignoring QC fail, secondary, supplemental, and PCR/optical duplicates.

**Comment by dpryan79** [comment]
This is now implemented in 0.1.13.
