### ISSUE TITLE
Adding pileometh to bioconda

### ISSUE THREAD

**Issue by HassanAmr** [dpryan79/PileOMeth#28]
Hi @bgruening  and @dpryan79 ,

I hope you don't mind if I add pileometh to bioconda.

Best regards,
Hassan

**Comment by bgruening** [comment]
This would be great!!!

**Comment by dpryan79** [comment]
:+1:, go for it! :)

**Comment by HassanAmr** [comment]
Thanks :)

**Comment by dpryan79** [comment]
This is now in bioconda, hope you don't mind that I went ahead and did it @HassanAmr :)

**Comment by HassanAmr** [comment]
@dpryan79, not at all. Sorry for the delay.
