### ISSUE TITLE
[fai_fetch_seq] The sequence "KI270728.1" not found

### ISSUE THREAD

**Issue by Divyagash** [dpryan79/PileOMeth#29]
When I tried to run mbias in one of the bam files, I got this error message and the `.svg` files are not generated.

`[fai_fetch_seq] The sequence "KI270728.1" not found`
`faidx_fetch_seq returned -2 while trying to fetch the sequence for tid 25 (KI270728.1)!`
`Note that the output will be truncated!`

Is this due to nonstandard chromosomes in the bam file ? How do I get around this problem?

**Comment by dpryan79** [comment]
Are you sure that's in your fasta file? It's likely not.

**Comment by Divyagash** [comment]
I checked my output and it seems like there are some problem with the reference sequence. After I changed the reference sequence I didn't see any error. So I think you can close the issue!

**Comment by dpryan79** [comment]
Great, thanks for the follow-up!
