### ISSUE TITLE
question about double-counting C's in overlap region

### ISSUE THREAD

**Issue by aloraine205** [dpryan79/PileOMeth#30]
Thank you for this incredibly useful tool!

I have  a question about how PileOMeth extract handles methylation metrics in regions where read1 and read2 from the same paired-end fragment overlap.

Because this is a question, I posted it on BioStars:

https://www.biostars.org/p/215908/

I am looking forward to hearing what you think!

**Comment by dpryan79** [comment]
Good question, I've replied on biostars. I wrote about this briefly in the README [here](https://github.com/dpryan79/PileOMeth#single-cytosine-methylation-metrics-extraction), but I really should expand on that (I'll leave this open until I have a chance to do that).

**Comment by dpryan79** [comment]
I've updated the readme file on github to go through how the various cases of overlaps are dealt with. Thanks for the note about this!
